### ISSUE TITLE
failure() doesn't work in a condition

### ISSUE THREAD

**Issue by arcivanov** [ChristopherHX/conditional#2]
```yaml
    - name: Print Logs on Failure
      uses: ChristopherHX/conditional@main
      with:
        if: ${{ failure() }}
        step: |
          shell: bash
          run: |
            for f in $(find . -name \*.log); do
                echo ">>>>>> $f"
                cat "$f"
            done
            exit 1
```

```
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/org/repo/./.github/action.yml (Line: 62, Col: 13): Unrecognized function: 'failure'. Located at position 1 within expression: failure()
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
```

**Comment by ChristopherHX** [comment]
It would be nice if this would work with my action, this action simply cannot run if previous steps of the action are failing. 

This is an action schema error, you cannot access job status functions inside a with block therefore you get that message from the runner. ( documentation https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability )

For your scenario you really need first level if support of the runner or consider a different approach:

However you can write a javascript action with a **post step** (https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post) which 
can run on failure after all steps are finished, then **call it in your composite action**.
It might be a good idea to create an action ( or find one ) which takes a script and shell, then execute it on success, failure or always.

Calling other actions on failure isn't possible with this method.

Here a sample javascript action which runs `post.js` if your  job fails after calling this action.

action.yml
```yaml
runs:
  using: node12
  main: main.js
  post: post.js
  post-if: failure()
```
main.js ( empty file )
```
```
post.js
```
console.log('print your log with node 12 or call bash yourself');
```

**Comment by arcivanov** [comment]
Interestingly enough I was able to query the previous step status as follows while staying within the composite:

https://github.com/pybuilder/pybuilder/blob/master/.github/action.yml#L64

**Comment by ChristopherHX** [comment]
I agree https://github.com/pybuilder/pybuilder/blob/master/.github/action.yml#L64 doesn't cause a job failure, but it also doesn't do what you want.

> steps.configure.output

This is always null, because steps doesn't have any output property in official runners ( see https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context )

I guess you wanted to use `steps.configure.outcome`, but in both cases your step will be skipped on failure, before my action can handle the if. ( `continue-on-error` is also unavailable )

_I recommend you to test your action locally with https://github.com/ChristopherHX/runner.server, then you can avoid committing changes of local actions and workflows during testing, it uses the same runner as github_

**Comment by arcivanov** [comment]
Yeah, thanks, it's definitely a typo. I was hoping to avoid JS and stick with composites but I guess there isn't a way to avoid it.

**Comment by ChristopherHX** [comment]
I think you can remove every workaround soon https://github.com/actions/runner/commit/67ba8a7d429d953396c08550d8590af9889c4efe and I may archive this repository.

v2.284.0 seems to be prepared for release.

_Official runnerlevel support is better than my hack_

**Comment by arcivanov** [comment]
Sweet, thanks!
